### ISSUE TITLE
Proposal: Add Database Migration Task

### ISSUE THREAD

**Issue by turp** [cake-contrib/Cake.SqlServer#51]
For many years, I have deployed database changes following the advice of Martin Fowler in an article a member of his team wrote https://www.martinfowler.com/articles/evodb.html. I've been performing this task using custom Ruby code for many years, but would like to have Cake perform these tasks.

The process is pretty straightforward:

- All application code (views, functions, procedures, and if you must, triggers) are stored in source code control. Each in their own folder. Each object in it's own script. Each script will contain everything needed to drop and recreate the object
- Schema changes (table creation/modification, indexes, constraints) are stored in a special folder called migrations. This folder contains scripts designed to be run only one time and in a specific order. Each script follows a naming convention: nnn_ScriptDescription.sql - where nnn is a number from 000 -> 999.

The migrate task itself does three major things:

- It checks the database for a schema_version table (creating it if it does not exist) to determine which migration scripts it needs to run.
- it then runs each migration script from source code control, in numerical order. After each script is run successfully, it updates the schema_version table with a new version number.
- once all of schema migrations have completed, all of the view, proc, function and trigger scripts are run against the database.
- an optional step can be invoked to remove views, procs, functions and triggers not stored in git.

I have found this to be an extremely simple and reliable process. It makes managing multiple local development databases as well as test, QA and production databases very easy. If a QA database has been updated in a few months, the migrate task will quickly bring the schema up-to-date.
 
I plan to start work on rev 0 of the code next week.

**Comment by turp** [comment]
I'll check out DbUp. Seems like I looked at it a long time ago, same with roundhouse, but don't remember why I didn't go down that path. EF is nice (some people on my team are using it), but we have a number of older applications that don't merit the effort to convert to EF.

**Comment by AdaskoTheBeAsT** [comment]
in my opinion functionality of db migration task shouldn't be part of that plugin as there are more mature above solutions for that maintained by lots of people...

**Comment by turp** [comment]
We can close this issue. Thanks
